### PR TITLE
Bit of a refactor of the helper

### PR DESCRIPTION
**Pull request by markburns**
Hi, 
Just wondering what you thought to this? I ran into some difficult to trace bug with the calendar helper and in trying to understand it gradually refactored it until I could make a little more sense of what was going on in the code.
Anyway there's a little more of an explanation in the commit message. 
Unfortunately, there were no unit tests on the existing code and so I can't guarantee it's bug free.
Well I suppose I can guarantee I've let a bug through. :-)
Is there a specific reason for not having tests on it that I should be aware of? Perhaps you weren't wanting to make them too brittle? I'm just thinking about possibly retroactively fitting some now so any heads up would be good.

### CODE REVIEW

**Comment by jeffschuil** [comment]
Browsed over your refactor, and it looks nice. I've noticed a couple of others have done something similar in the past, but I felt they made things overly complicated (w/ presentation models etc..). My goal has always been to keep this thing fairly simple. Your refactor seems to strike a good balance.

The advantage, of course, in breaking that large method up as you've done is it makes it much easier to test. That was the main reason I hadn't gotten to adding any before. Though brittle tests are always a concern, there is no reason I can think of to stop you from adding tests, if you're so inclined.

I hope to look over the changes in more detail soon and get them into master. Thanks!

**Comment by markburns** [comment]
OK. I think perhaps I should have done a few extract method refactors per commit. Would make it easier to confirm that I've not introduced any obvious bugs. I've also noticed that somehow my fork is forked a few commits back from master. Not sure how that happened. I might have a look at this maybe tomorrow and maybe rework it and add in some tests. Unless you've already merged it in or are in the process of doing so.

**Comment by jeffschuil** [comment]
I haven't done any merging yet.

**Comment by yrral86** [comment]
I ran into the same error... I switched to 2.3.3 + the first commit here, then I figured out what I was doing wrong.  In my case, I had a mismatch between @shown_month and the month I was passing to event_strips_for_month.  I'm not sure if that's useful or not, but I figured I'd share the info.

**Pull request closed without merging**
